### ISSUE TITLE
Bug due to NamedTemporaryFile on windows

### ISSUE THREAD

**Issue by tim-mccurrach** [loftylabs/django-hardcopy#6]
Using django-hardcopy, with windows 10, and python 3.6 I have found that it just hangs on the subprocess.call(). I think the reason for this is that, when python creates a NamedTemporaryFile, in NT it is created with the FILE_SHARE_DELETE flag, so that windows (not python) automatically deletes the file after it is closed. It also allows, the file to be opened a second time, when already open but it has to be opened with the FILE_SHARE_DELETE flag. As a result chrome can’t write to it or overwrite it. Fortunately, Django have created there own NamedTemporaryFile, (see [here](https://code.djangoproject.com/wiki/NamedTemporaryFile) and [here](https://github.com/django/django/blob/master/django/core/files/temp.py))

Replacing this line:
`from tempfile import NamedTemporaryFile`
with this:
`from django.core.files.temp import NamedTemporaryFile`
fixes everything for me. I have not tested this on any other operating systems, but it doesn’t look like it would cause any issues.

**Comment by ztroop** [comment]
> This is needed because the Python implementation of NamedTemporaryFile uses the
O_TEMPORARY flag under Windows, which prevents the file from being reopened
if the same flag is not provided [1][2]. Note that this does not address the
more general issue of opening a file for writing and reading in multiple
processes in a manner that works across platforms.
The custom version of NamedTemporaryFile doesn't support the same keyword
arguments available in tempfile.NamedTemporaryFile.
1: https://mail.python.org/pipermail/python-list/2005-December/336957.html
2: http://bugs.python.org/issue14243

sauce: https://github.com/django/django/blob/master/django/core/files/temp.py

It has the potential to cause problems, as not all keyword arguments are supported. However, in our use case it does not appear to cause any problems. I'll create a PR, and the maintainers can decide if they want to merge it.

**Comment by ckinsey** [comment]
A fix for this has been merged and will land in the next release.
