### ISSUE TITLE
Unable to run on linux if none of the LINUX_PATHS is present

### ISSUE THREAD

**Issue by hcastilho** [loftylabs/django-hardcopy#9]
Independently of CHROME_PATH being set conf.get_chrome_path is always called.
If the system has none of the default paths exists this raises a ValueError.
conf.get_chrome path should only be called if CHROME_PATH is not defined.

**Comment by ztroop** [comment]
Un momento por favor. I'll have a PR up shortly to address that.

**Comment by ztroop** [comment]
Actually, I know exactly is happening here. Before `getattr` runs, all functions exposed as parameters are evaluated. This happens regardless if the attribute is found or not, which is producing this issue. I'll produce a PR to properly handle this.

**Comment by ckinsey** [comment]
A fix for this has been merged and will land in the next release.  Thanks @ztroop!

**Comment by alchemyconsulting** [comment]
Hi, I've just hit the same problem.  A popular way of installing headless chrome on AWS Linux is:
https://intoli.com/blog/installing-google-chrome-on-centos/
This installs into /usr/bin/google-chrome-stable, so triggers this.
Would be great if you could cut a release to include this fix.

**Comment by alchemyconsulting** [comment]
```
LINUX_PATHS = [
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/chrome',
    '/usr/bin/chrome-browser',
]
```
For now need to symlink /usr/bin/google-chrome-stable to /usr/bin/chrome, until above issue is fixed.

**Comment by ckinsey** [comment]
@alchemyconsulting  We can add `google-chrome-stable` to the default `LINUX_PATHS` list in the next release.

This is only used for some sane defaulting that makes the app as plug and play as possible--in the meantime, rather than symlinking you can always set `CHROME_PATH = '/usr/bin/google-chrome-stable'` explicitly in your Django settings which bypasses the path guessing logic entirely.

**Comment by ztroop** [comment]
Hi, @alchemyconsulting, as @ckinsey had already mentioned. The symlink is *not required*. If you add `CHROME_PATH = '/usr/bin/google-chrome-stable'` to your `settings.py`, you can override the assumptions made for sane defaults.

**Comment by alchemyconsulting** [comment]
Guys, I'm setting CHROME_PATH.  But it's still failing due to the bug in this issue.

**Comment by tapionx** [comment]
@alchemyconsulting i got the same problem.
This issue has been fixed into master, but the pip package has not been updated since.
I bypassed the issue installing the pip package using the github URL.
Maintainers, could you please update the pip package?

**Comment by ztroop** [comment]
What version of the package are you guys using? `django-hardcopy-0.1.4` should be sufficient for this configuration.
```
class HardCopyConfig(object):
    CHROME_PATH = (
        settings.CHROME_PATH
        if hasattr(settings, 'CHROME_PATH')
        else get_chrome_path())
    ...
```

**Comment by alchemyconsulting** [comment]
pip is installing 0.1.3

**Comment by ckinsey** [comment]
0.1.4 was just released this morning--it includes this fix as well as a few others that were merged, but unfortunately not released to pip due to an oversight.

**Comment by alchemyconsulting** [comment]
Thanks, 0.1.4 works as expected now :)
